.Dd $Mdocdate$
.Dt globalgrep 1
.Os OpenBSD 7.0
.Sh NAME
.Nm globalgrep
.Nd search for stuff on multiple network hosts
.Sh SYNOPSIS
.Nm globalgrep
.Ar query
.Sh DESCRIPTION
.Nm globalgrep
is a tool which facilitates searching through files on multiple network
hosts.  As of the writing of this sentence,
.Nm globalgrep
is really just a frontend for
.Xr grep 1 ;
however,
.Nm globalgrep
should still be at least marginally useful.
.Pp
If
.Pa $PATH/.config/globalgrep
is a file which contains only a space-separated list of network
hosts which can be accessed via passwordless SSH connections,
then for all network hosts which are specified in
.Pa $PATH/.config/globalgrap ,
the command
.Dl globalgrep query
runs the command
.Dl grep ri query /
on a network host, writing the output of this command to the
standard output.
.Sh NOTES
.Nm globalgrep
assumes that all systems which are searched use the same log-in
username.  VARIK is willing to modify
.Nm globalgrep
such that
.Nm globalgrep
supports per-host usernames if any users of
.Nm globalgrep
would benefit from such modification.
.Sh AUTHOR
.Nm globalgrep
is maintained by
.An Varik
.An Dq NOT A COMPUTER PROGRAMMER!!!
.An Valefor
.Aq varikvalefor@aol.com .
Feature requests and patches are welcomed... but may go unused.
